- .eslintrc.js
- LICENSE
- README.md
- package.json
- yarn.lock
* Expand on requirements
* Makes prettier less offensive and more auto fixing issues
Closes #10
> Expand documentation to make it easier to contribute

- app/javascript/components/Common/Form/Input.js
- app/javascript/components/Merchant/GenerateForm.js
- app/javascript/components/Merchant/index.js
UI setup for merchant form 
Relates to #5
> Merchant Form UI

- app/javascript/components/Common/Button/index.js
- app/javascript/components/Common/Form/Input.js
- app/javascript/components/Merchant/GenerateForm.js
- package.json
- yarn.lock
Relates to #5 
* Adds common button component
* Adds error for common input component
* Validate merchant form on frontend
> Merchant form UI enhancements

- app/javascript/components/Merchant/DisplayQr.js
- app/javascript/components/Merchant/index.js
- app/javascript/components/Merchant/useGetQrUrl.js
- app/javascript/hooks/useQuery.js
- app/views/home/index.html.slim
- config/webpack/custom.js
- tailwind.config.js
* UI for displaying merchant QR code
* Allow for print styles
Relates to #5
> Display QR code with Merchant ID

- app/javascript/components/Common/Button/index.js
- app/javascript/components/Common/Spinner.js
- app/javascript/components/Merchant/GenerateForm.js
- tailwind.config.js
* Loading indicator for button
* Disabled styles for button
> Add common loading indicator to button

- app/javascript/apis/axios.js
- app/javascript/components/Admin/SignIn.js
- app/javascript/components/Admin/index.js
- app/javascript/components/User/Scan/index.js
- app/javascript/components/User/SignUp/SignUp.js
* Add admin sign in page
* Add autocomplete attributes for forms
Relates to #7
> Admin Login Page UI

- lib/tasks/setup.rake
> Fixes bin/setup task

- app/javascript/components/User/Scan/QrScanner.js
- app/javascript/components/User/Scan/index.js
also removed unwanted console log used in QRcode scan component
> adds the logout button for the user

- app/controllers/api/v1/sessions_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/controllers/home_controller.rb
- app/helpers/application_helper.rb
- app/javascript/apis/Admin/Auth.js
- app/javascript/apis/authentication.js
- app/javascript/components/Admin/SignIn.js
- app/javascript/components/User/SignUp/SignUp.js
- app/javascript/components/User/SignUp/SignUpOtp.js
- Skip auth token checks on user sign up flows
- Integrate OTP 
- Integrate admin sign in
> UI correct sign in flows

- app/controllers/api/v1/sessions_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/models/user.rb
- test/controllers/api/v1/users_controller_test.rb
- FIxes test failures
- Adds `authentication_token` to `verify_otp` API response.
> Fix test failures

- app/javascript/components/User/Home/VisitCard.js
> Add address, border to visit card

- app/views/api/v1/visits/_visit.json.jbuilder
Fixes #57 
- Added visit_id to visit api response
@agneym _a
> Added visit_id to visit api

- app/javascript/components/Admin/AdminHome.js
- app/javascript/components/Admin/Header.js
- app/javascript/components/Admin/SignIn.js
> Admin logout

- app/controllers/api/v1/merchants_controller.rb
- app/javascript/components/Merchant/DisplayQr.js
- app/javascript/components/User/Home/Content.js
- app/javascript/components/User/Home/VisitCard.js
- app/javascript/components/User/SignUp/SignUp.js
* removes authentication check from merchant API
* fixes on visit card UI
> Remove authentication from merchant API

- app/javascript/apis/Admin/index.js
- app/javascript/components/Admin/AdminHome.js
- app/javascript/components/Admin/RouteMap.js
- app/javascript/components/Admin/Sidebar.js
- app/javascript/components/Admin/index.js
- app/javascript/components/Merchant/index.js
- app/javascript/components/User/Home/Content.js
- app/javascript/components/User/Home/index.js
- app/javascript/components/User/Scan/index.js
- app/javascript/components/User/SignUp/SignUp.js
- package.json
- yarn.lock
* Add route map view for admin
* correct date validation in yup for sign up form
> Add route map view for admin

- config/initializers/rack_deflater.rb
Fixes #50 
Explanation: https://share.getcloudapp.com/DOuA0Aej
> Fixes API response compression with GZIP

- app/javascript/components/Merchant/GenerateForm.js
- app/javascript/components/User/Scan/index.js
`const { id } = JSON.parse(qrData);`
Earlier id was only expecting. Now changed to the JSON structure as it is encoded in the merchant side.
> Parse id from qr data after scanning

- app/javascript/apis/Admin/index.js
- app/javascript/components/Admin/AdminHome.js
- app/javascript/components/Admin/RouteMap.js
Authentication fix in Admin side
User route map fetched based on phone and date.
Addresses [issue](https://github.com/coronasafe/journal/issues/8)
> User route map added to admin

- app/javascript/components/User/Home/Content.js
- app/javascript/components/User/Home/Header.js
User name displayed and style fix
> ui improvements in user dashboard

- app/views/api/v1/admin/users/route_map.json.jbuilder
- doc/api.md
- test/controllers/api/v1/admin/users_controller_test.rb
> User'name added in the routemap api response

- app/javascript/apis/Admin/index.js
- app/javascript/components/Admin/RouteMap.js
User name added on fetching route - map of the user.
Style improvement
[Issue](https://github.com/coronasafe/journal/issues/8) fixed
> user name added in route-map

- app/controllers/api/v1/admin/merchants_controller.rb
- app/models/merchant.rb
- app/views/api/v1/admin/merchants/_merchant.json.jbuilder
- app/views/api/v1/admin/merchants/index.json.jbuilder
- config/routes/api.rb
- doc/api.md
- test/controllers/api/v1/admin/merchants_controller_test.rb
- test/models/merchant_test.rb
API doc: https://github.com/unnitallman/journal/blob/70-filtered-merchants-list/doc/api.md#merchants-filter
> Merchants filter API 

- app/javascript/apis/MerchantApi/index.js
- app/javascript/apis/merchants.js
- app/javascript/apis/utilities.js
- app/javascript/components/Common/Form/Input.js
- app/javascript/components/Common/Form/Label.js
- app/javascript/components/Common/Form/Select.js
- app/javascript/components/Common/Form/SelectController.js
- app/javascript/components/Merchant/GenerateForm.js
- app/javascript/components/Merchant/LocalBodyForm.js
- package.json
- yarn.lock
* Add `react-select`
* Cascading select for district, local body type, local body
Closes #71
> Select local body for merchant

- app/javascript/apis/Admin/index.js
- app/javascript/components/Admin/Establishments/index.js
- app/javascript/components/Admin/RouteMap.js
Adds the route map from , to dates and the validations
Establishment 'to'feild minimum date validation
Fixes #76
> Rout map dates

- app/javascript/apis/Admin/index.js
- app/javascript/components/Admin/AdminHome.js
- app/javascript/components/Admin/Establishments/EstList.js
- app/javascript/components/Admin/Establishments/EstSearch.js
- app/javascript/components/Admin/Establishments/List.js
- app/javascript/components/Admin/Establishments/VisitorRegister.js
- app/javascript/components/Admin/RouteMap.js
- app/javascript/components/Common/LocalBodyForm.js
- app/javascript/components/Common/Table/index.js
- app/javascript/components/Merchant/GenerateForm.js
- app/views/api/v1/admin/users/_route_map_visit.json.jbuilder
* Admin is routed to establishments page where they can filter by local body
* Selecting an establishment page leads to detail where visitor register is displayed given a specific from and to dates
* Admin can route from route map page to establishment visitor register page
> Rearrange admin establishments

- app/controllers/api/v1/merchants_controller.rb
- app/models/concerns/otp_verifiable.rb
- app/models/merchant.rb
- app/models/user.rb
- app/views/api/v1/admin/merchants/_merchant.json.jbuilder
- app/views/api/v1/admin/merchants/index.json.jbuilder
- app/views/api/v1/merchants/create.json.jbuilder
- config/routes/api.rb
- db/migrate/20200728080517_add_otp_token_to_merchants.rb
- db/migrate/20200728083700_add_temp_id_for_merchants.rb
- db/schema.rb
- doc/api.md
- test/controllers/api/v1/merchants_controller_test.rb
- test/models/merchant_test.rb
Related to #6 
1. Made changes in in Merchant creation API: https://github.com/unnitallman/journal/blob/6-merchant-otp-verification/doc/api.md#create-a-merchant
2. Added the Merchant OTP verification API: https://github.com/unnitallman/journal/blob/6-merchant-otp-verification/doc/api.md#merchant-otp-verification
> Merchant OTP verification

- app/controllers/api/v1/merchants_controller.rb
- app/javascript/apis/MerchantApi/index.js
- app/javascript/components/Merchant/GenerateForm.js
- app/javascript/components/Merchant/VerifyOtp.js
- app/javascript/components/Merchant/index.js
> Merchant OTP page
